about/urls.py
from django.urls import path
from .views import about_view

app_name = "about"

urlpatterns = [
    path("about/", about_view, name="about")
]

brands/urls.py
from django.urls import path
from . import views

app_name = 'brands'

urlpatterns = [
    path('brands/', views.brand_view, name='brands'),
    path('brands/<str:tab>/', views.brand_view, name='brands_tab'),

]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.http import HttpResponse
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

def robots_txt(request):
    lines = [
        "User-agent: *",
        "Disallow: /admin/",
        "Disallow: /api/",
        "Disallow: /media/private/",
        "",
        # "Sitemap: https://maximum.de/sitemap.xml"
    ]
    return HttpResponse('\n'.join(lines), content_type="text/plain")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('i18n/', include('django.conf.urls.i18n')),  
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', robots_txt),
]

urlpatterns += i18n_patterns(
    path('', include('home.urls')),
    path('', include('product.urls')),
    path('', include('services.urls')),
    path('', include('about.urls')),
    path('', include('partnership.urls')),
    path('', include('faq.urls')),
    path('', include('news.urls')),
    path('', include('brands.urls')),
    path('', include('contact.urls')),
    path('', include('search.urls')),
    prefix_default_language=False
    )

urlpatterns += [
    re_path(r'^rosetta/', include('rosetta.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0] if settings.STATICFILES_DIRS else settings.STATIC_ROOT)

handler404 = 'home.views.handler404'
handler403 = 'home.views.handler403'
handler500 = 'home.views.handler500'
handler503 = 'home.views.handler503'

faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('faq/', views.faq_view, name='faq'),
]

home/urls.py
from django.urls import path
from .views import home_view, submit_review

app_name = "home"

urlpatterns = [
    path("", home_view, name="home"),
    path("submit-review/", submit_review, name="submit_review"),

]

news/urls.py
from django.urls import path
from . import views   

app_name = 'news'

urlpatterns = [
    path('news/', views.news_list, name='news'),
    path('news/<slug:slug>/', views.news_detail, name='news_detail'),
]

templates/components/contact_section.html
{% load static %} {% load i18n %}

<section class="container about-section-contact">
  <div class="contact-text">
    <p>
      Interested in <br />
      working with us?
    </p>
    <a href="{% url 'contact:contact_step_two'%}" class="button-style"
      >{% trans "Contact us" %}</a
    >
  </div>
</section>

templates/components/featured_products.html
{% load static %}
{% load i18n %}


<section class="featured-products container">
  <div class="top-content">
    <h2 class="section-title">FEATURED PRODUCTS</h2>
     {% if products_description %}
      <p class="section-desc">{{  products_description|linebreaksbr }}</p>
      {% else %}
    <p class="section-desc">
      Explore our extensive portfolio of over 400 premium lubricants and service fluids — engineered
      for exceptional performance, protection, and efficiency.
    </p>
    {% endif %}
  </div>

  <div class="products-container">
    <div class="main-product">
      <img src="{{ products_background }}" alt="NOVALUBE PRO 0W-30" />
      <a href="" class="button-style">
        Go to catalog
        <i class="fa-solid fa-arrow-right"></i>
      </a>
    </div>

    <div class="products-swiper-container">
      <div class="swiper productsSwiper">
        <div class="swiper-wrapper">
         {% for product in featured_products %}
            <a href="{% url 'product:product_detail' slug=product.slug %}" class="swiper-slide">
                <div class="product-image">
                <img src="{{ product.image.url }}" alt="{{ product.title|linebreaksbr  }}" />
                </div>
                <div class="product-content">
                <h3 class="product-name">{{ product.title|linebreaksbr }}</h3>
                <p class="product-specs">{{ product.oil_type|linebreaksbr }}</p>
                </div>
            </a>
          {% empty %}
            <a href="#" class="swiper-slide">
                <p class="product-specs">{% trans "No products available at the moment" %}</p>
            </a>
          {% endfor %}


        </div>
      </div>
    </div>
  </div>

  <div class="product-navigation">
    <div class="product-swiper-button-prev">
      <i class="fa-solid fa-arrow-left-long"></i>
    </div>
    <div class="product-swiper-button-next">
      <i class="fa-solid fa-arrow-right-long"></i>
    </div>
  </div>
</section>


{%block page_js %}
    <script src="{% static 'assets/js/component-swiper.js' %}" defer></script>
{% endblock %} 

templates/components/footer.html
{% load static %}
{% load i18n %}

<footer>
  <div class="container">
    <div class="footer-content">
      <div>
          <a href="{% url 'home:home' %}" class="maximum-logo" aria-label="Home Page">
            <img loading="lazy"  src="{% static '/images/maximum-logo.webp' %}" alt="Maximum logo" />
          </a>
      </div>
      <div class="footer-row">
          <ul>
              <li>
                <div>
                  <a href="{% url 'about:about' %}" aria-label="About Page">{% trans "About Us" %}</a>
                  <a href="{% url 'product:products' %}" aria-label="Products Page">{% trans "Products" %}</a>
                </div>
                <div>
                  <a href="" aria-label="Service Page">{% trans "Services" %}</a>
                  <a href="" aria-label="Brand Portal Page">{% trans "Brand Portal" %}</a> 
                </div>
              </li>
              <li>
                <div>
                  <a href="{% url 'news:news' %}" aria-label="News Page">{% trans "News" %}</a>
                  <a href="{% url 'faq:faq' %}" aria-label="Faq Page">{% trans "FAQ" %}</a>
                </div>          
                <div>
                  <a href="{% url 'partnership:partnership' %}" aria-label="Partnership Page">{% trans "Partnership" %}</a>
                  <a href="" aria-label="Contact Page">{% trans "Contact" %}</a>
                </div>
              </li>
          </ul>
          <button id="scrollToTop" aria-label="Scroll to top"><i class="fa-solid fa-chevron-up"></i></button>
      </div>
    </div>

    <div class="footer-contact">
      <div>
        <p>{% trans "Leopoldstrasse 244, 80807 München, Germany" %}</p>
        <div class="phone-number">(+49) 711 490 66 222</div>
        <p>info@maximumlube.de</p>
      </div>
      <div class="">
        <a href="https://wa.me/4915207776502" aria-label="Whatsapp Page">
          <img loading="lazy"   src="{% static 'images/whatsapp.webp' %}" alt="Whatsapp" />
        </a>
        <a href="#" aria-label="Youtube Page"  target="_blank" >
          <img loading="lazy"   src="{% static 'images/youtube.webp' %}" alt="Youtube" />
        </a>
        <a href="#" aria-label="Linkedin Page">
          <img loading="lazy"   src="{% static 'images/linkedin.webp' %}"  target="_blank" alt="Linkedn" />
        </a>
        <a href="#" aria-label="Instagram Page" target="_blank">
          <img loading="lazy"   src="{% static 'images/instagram.webp' %}" alt="Instagram" />
        </a>
        <a href="#" aria-label="Facebook Page" target="_blank">
          <img loading="lazy"   src="{% static 'images/facebook.webp' %}" alt="Facebook" class="facebook" />
        </a>
      </div>
    </div>
    <hr class="custom-hr" />
    <div class="alco-privacy">
      <p>{% trans "© 2025 ALCO LLC. All right reserved." %}</p>
      <p>{% trans "Terms and Condition" %} - {% trans "Privacy Policy" %}</p>
    </div>
  </div>
</footer>

templates/components/navbar.html
{% load static %} {% load i18n %}

<meta name="csrf-token" content="{{ csrf_token }}" />

<nav>
    <div class="navbar ">
      <div class="container">
        <div class="nav-top">
          <a href="{% url 'home:home' %}" class="maximum-logo">
            <img loading="lazy" src="{% static '/images/maximum-logo.webp' %}" alt="Maximum logo"/>
          </a>

          <div class="search">
              <form method="GET" class="search-form" action="{% url 'search:search' %}">
                  <input type="text" name="search" value="{{ query }}" placeholder="{% trans 'Search...' %}" />
                  <button type="button" class="search-button">
                      <i class="fa-solid fa-magnifying-glass"></i>
                  </button>
              </form>
          </div>

          <div>
            <ul>
              <li> <a href="{% url 'brands:brands' %}" aria-label="Brand Portal Page"> {% trans "Brand Portal" %}</a></li>
              <li><a href="{% url 'news:news' %}" aria-label="News Page">{% trans "News" %}</a></li>
            </ul>
            <div class="language-dropdown">
              <button class="lang-dropdown-btn">
                {% get_current_language as CURRENT_LANGUAGE %}
                {% if CURRENT_LANGUAGE == 'en' %}EN 
                {% elif CURRENT_LANGUAGE == 'de' %}DE 
                {% elif CURRENT_LANGUAGE == 'es' %}ES 
                {% elif CURRENT_LANGUAGE == 'fr' %}FR 
                {% elif CURRENT_LANGUAGE == 'it' %}IT 
                {% elif CURRENT_LANGUAGE == 'zh-hans' %}汉语 
                {% else %}EN
                {% endif %}
                <i class="fa-solid fa-angle-down"></i>
              </button>
              <div class="dropdown-content" id="languageDropdown">
                {% get_available_languages as LANGUAGES %} 
                {% get_current_language as CURRENT_LANGUAGE %} 
                {% for lang_code, lang_name in LANGUAGES %}
                <button class="lang-option {% if lang_code == CURRENT_LANGUAGE %}active{% endif %}" data-lang="{{ lang_code }}">
                  {% if lang_code == 'en' %}EN 
                  {% elif lang_code == 'de' %}DE 
                  {% elif lang_code == 'es'%}ES 
                  {% elif lang_code == 'fr' %}FR 
                  {% elif lang_code == 'it' %}IT 
                  {% elif lang_code == 'zh-hans' %}汉语 
                  {% else %}{{ lang_code|upper }}
                  {% endif %}
                </button>
                {% endfor %}
              </div> 
            </div>
          </div>
        </div>
        <div class="nav-bottom">
            <ul>
                <li><a class="active" href="{% url 'product:products' %}" aria-label="Products Page">{% trans "Products" %}</a></li>
                <li><a href="{% url 'about:about' %}" aria-label="About Page">{% trans "About us" %}</a></li>
                <li><a href="{% url 'services:services' %}" aria-label="Services Page">{% trans "Services" %}</a></li>
                <li><a href="{% url 'partnership:partnership' %}" aria-label="Partnership Page">{% trans "Partnership" %}</a></li> 
                <li><a href="{% url 'contact:contact' %}" aria-label="Contact Page">{% trans "Contact" %}</a></li>
            </ul>
          <a href="" class="location-icon">
              <img loading="lazy" class="icon" src="{% static '/images/location.svg' %}" alt="Location icon"/>
          </a>       
        </div>
        <button class="hamburger" aria-label="Menu" id="hamburger">
          <i class="fas fa-bars"></i>
        </button>
      </div>
    </div>


<div class="mobile-menu" id="mobile-menu">
  <ul>
    <li><a href="{% url 'product:products' %}" aria-label="Products Page">{% trans "Products" %}</a></li>
    <li><a href="{% url 'about:about' %}" aria-label="About Page">{% trans "About us" %}</a></li>
    <li><a href="{% url 'services:services' %}" aria-label="Services Page">{% trans "Services" %}</a></li>
    <li><a href="{% url 'partnership:partnership' %}" aria-label="Partnership Page">{% trans "Partnership" %}</a></li>
    <li><a href="{% url 'contact:contact' %}" aria-label="Contact Page">{% trans "Contact" %}</a> </li>
    <li><a href="{% url 'brands:brands' %}" aria-label="Brand Portal Page">{% trans "Brand Portal" %}</a></li>
    <li><a href="{% url 'news:news' %}" aria-label="News Page">{% trans "News" %}</a></li>
  </ul>
  <div class="mobile-menu-bottom">
    <a href="" class="location-icon">
        <img loading="lazy" src="{% static '/images/location.svg' %}" alt="Location icon"/>
    </a>  

    <a class="whatsapp" href="#">
      <p>{% blocktrans %} Have a question? <br> Let's chat on WhatsApp!{% endblocktrans %}</p>
      <img loading="lazy" src="{% static '/images/whatsapp.svg' %}" alt="Whatsapp icon"/>
    </a>

  </div>
</div> 
</nav>

templates/components/page-header.html
{% load static %}
{% load i18n %}
  
{% if page_header %}
<header class="page-header container">
            <img class="background-image" src="{{ page_header.image.url }}"
                 alt=" Page header -{{ page_header.slug }}" loading="lazy"/> 

             <a class="whatsapp" href="#">
                <p>{% blocktrans %} Have a question? <br> Let's chat on WhatsApp!{% endblocktrans %}</p>
                <img loading="lazy" src="{% static '/images/whatsapp.svg' %}" alt="Whatsapp icon"/>
             </a>
</header>
{% endif %}

templates/components/partners.html
{% load static %}
{% load i18n %}

<section class="our-partners container">
        <div class="top-content">
            <h2 class="section-title">{% blocktrans %}  Our Partners {% endblocktrans %} </h2>
             {% if partners_description %}
            <p class="section-desc">{{  partners_description|linebreaksbr }}</p>
            {% else %}
            <p class="section-desc">{% blocktrans %} Remittance acts as a bridge, connecting loved ones and making the world a little smaller. We are dedicated to forging strategic partnerships which help us help you send money around the globe quickly, safely and affordably. {% endblocktrans %}</p>
            {% endif %}
        </div>  
        <div class="swiper-wrapper-container">
            <div class="partners-swiper-button-prev"><i class="fa-solid fa-arrow-left-long"></i></div>
                <div class="swiper partnersSwiper">
                    <div class="swiper-wrapper">
                        {% for partner_logo in partner_logos %}
                            <div class="swiper-slide">
                                <img loading="lazy" src="{{ partner_logo.logo.url }}" width="155" height="70"
                                    alt="{{ partner_logo.name }}"  />
                            </div>
                        {% endfor %}
                    </div>                         
                </div>
            <div class="partners-swiper-button-next"><i class="fa-solid fa-arrow-right-long"></i></div>
        </div>
</section>

{%block page_js %}
    <script src="{% static 'assets/js/component-swiper.js' %}" defer></script>
{% endblock %} 